#!/usr/bin/env bash
set -eu -o pipefail

die() {
    local exitcode=$1
    echo 2>&1 ERROR: "$@"
    exit $exitcode
}

basedir=$(cd "$(dirname "$0")" && pwd -P)

cd "$basedir"
. ./activate
pytest -q "$@"

out="$basedir/.build/dns_client.out"
args="-d yahoo.com -r MX -s 8.8.8.8"

python dns_client.py $args > "$out" || die 1 'FAILED: bad exit'
grep -s 'yahoodns.net' "$out" || die 1 'FAILED: bad output'

echo OK
